### ISSUE TITLE
Adding a License

### ISSUE THREAD

**Issue by kyonofx** [Sangwon91/PORMAKE#1]
Hi,

Thank you very much for open-sourcing this amazing repo! Would you consider adding a license? e.g. the MIT License.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Thanks!

**Comment by Sangwon91** [comment]
Good suggestion. I have added the license (MIT).
Thank you.
