### ISSUE TITLE
Information on geometry optimization: MOF Construction

### ISSUE THREAD

**Issue by MR1319** [Sangwon91/PORMAKE#22]
Hi @Sangwon91 and @aniruddha-seal,

I'm writing to inquire about the implementation of geometry optimization during the construction of MOFs. I'm currently working on implementing your code for database creation and I'm unsure whether geometry optimization is automatically performed during the MOF construction process or if it needs to be addressed separately using UFF4MOF force field using LAMMPS. 

Thanks, 
Madhav

**Comment by Sangwon91** [comment]
Hi, MR1319.

You can find information on topology optimization in the  [supporting information section S2](https://pubs.acs.org/doi/suppl/10.1021/acsami.1c02471/suppl_file/am1c02471_si_001.pdf) of the original paper. No force fields are used; rather, it is a simple geometric optimization based on the sizes and shapes of building blocks.

**Comment by MR1319** [comment]
Thanks @Sangwon91, for clarification on the optimization. 

Closing this issue.
