### ISSUE TITLE
about pickle

### ISSUE THREAD

**Issue by Yong-Q** [Sangwon91/PORMAKE#23]
FileNotFoundError: [Errno 2] No such file or directory: '.conda/envs/pormake/lib/python3.9/site-packages/pormake/database/topologies/wfz.pickle'

Unable to find the pickle file in the database, why is that? How to solve it?

**Comment by Sangwon91** [comment]
It seems like a print error. Although an error is printed, you should be able to obtain the topology. I will work on fixing this bug.
