### ISSUE TITLE
pickle for bbs

### ISSUE THREAD

**Issue by Yong-Q** [Sangwon91/PORMAKE#24]
I want to convert bbs and topo to pickle format, but it seems only topo can be converted. I encountered the following error:

.conda/envs/pormake/lib/python3.9/site-packages/pormake/database.py", line 30, in __init__
    if not self.bb_dir.exists():
AttributeError: 'str' object has no attribute 'exists'

**Comment by Sangwon91** [comment]
I have fixed all bugs you mentioned (both in GitHub and PyPI).
Thank you!
