### ISSUE TITLE
Duplicate building blocks

### ISSUE THREAD

**Issue by johannbrehmer** [Sangwon91/PORMAKE#30]
First, thanks for a super useful library!

Is it possible that some building blocks in the library are duplicates of each other?

I'm pretty sure that [E23](https://github.com/Sangwon91/PORMAKE/blob/main/pormake/database/bbs/E24.xyz) and [E24](https://github.com/Sangwon91/PORMAKE/blob/main/pormake/database/bbs/E24.xyz) are duplicates (they are just a permutation of each other?)

The same may be true for [E12](https://github.com/Sangwon91/PORMAKE/blob/main/pormake/database/bbs/E12.xyz) and [E36](https://github.com/Sangwon91/PORMAKE/blob/main/pormake/database/bbs/E36.xyz), but I haven't checked carefully.

**Comment by Sangwon91** [comment]
Thank you for your valuable feedback. In the case of E23 and E24, the order of the connection points is different, which may result in a different shape for the generated MOF. Structurally, however, they are the same.

As for the other node pairs you mentioned, the bonding between atoms differs. Even if the molecular structures are similar, differences in atomic connectivity can lead to optimization into distinct MOF structures. Therefore, I assigned them as different building blocks.

Thank you!

**Comment by johannbrehmer** [comment]
Thanks for the fast reply! That makes sense.
