### ISSUE TITLE
'UserWarning: Optimal rotation is not uniquely or poorly defined for the given sets of vectors'

### ISSUE THREAD

**Issue by KP-303** [Sangwon91/PORMAKE#6]
When building a MOF with edges I often get this warning. 

For example, here I make a MOF using the 'tsg' topology. The three node building blocks I have selected are ones that have the correct number of connection points and they have an RMSD of < 0.3 with the relevant local structure.

`import pormake as pm
node_0_name='N10'
node_1_name='N216'
node_2_name='N421'

edge_0_name='E196'
edge_1_name='E51'

database=pm.Database()

node_0=database.get_building_block(node_0_name)
node_1=database.get_building_block(node_1_name)
node_2=database.get_building_block(node_2_name)

edge_0=database.get_building_block(edge_0_name)
edge_1=database.get_building_block(edge_1_name)

nodes=[node_0,node_1,node_2]

edges={(0,1): edge_0, (1,2): edge_1}

database=pm.Database()
tsg=database.get_topology('tsg')

builder=pm.Builder()

mof=builder.build_by_type(topology=tsg,node_bbs=nodes,edge_bbs=edges)
`
I get this output:

>>> == Min RMSD of (node type: 0, node bb: N10): 1.21E-05
>>> Pre-location at node slot 0, (node type: 0, node bb: N10), RMSD: 2.36E-05
>>> RMSD > MIN_RMSD*1.01, relocate Node 0 with 216 trial orientations, RMSD: 2.36E-05
>>> RMSD > MIN_RMSD*1.01, relocate Node 0 with 216 trial orientations and chiral building block, RMSD: 1.21E-05
>>> == Min RMSD of (node type: 1, node bb: N216): 4.79E-02
>>> Pre-location at node slot 1, (node type: 1, node bb: N216), RMSD: 1.62E-01
>>> RMSD > MIN_RMSD*1.01, relocate Node 1 with 216 trial orientations, RMSD: 4.79E-02
>>> Pre-location at node slot 2, (node type: 1, node bb: N216), RMSD: 1.21E-01
>>> RMSD > MIN_RMSD*1.01, relocate Node 2 with 216 trial orientations, RMSD: 4.79E-02
>>> Pre-location at node slot 3, (node type: 1, node bb: N216), RMSD: 1.21E-01
>>> RMSD > MIN_RMSD*1.01, relocate Node 3 with 216 trial orientations, RMSD: 4.79E-02
>>> == Min RMSD of (node type: 2, node bb: N421): 1.39E-01
>>> Pre-location at node slot 4, (node type: 2, node bb: N421), RMSD: 1.39E-01
>>> Topology optimization starts.
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
>>> MESSAGE: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
>>> SUCCESS: True
>>> ITER: 83
>>> OBJ: 0.019
>>> Location at node slot 0, (node type: 0, node bb: N10), RMSD: 1.47E-03
>>> Location at node slot 1, (node type: 1, node bb: N216), RMSD: 1.68E-01
>>> Location at node slot 2, (node type: 1, node bb: N216), RMSD: 1.62E-01
>>> Location at node slot 3, (node type: 1, node bb: N216), RMSD: 1.74E-01
>>> Location at node slot 4, (node type: 2, node bb: N421), RMSD: 8.29E-02
>>> Start placing edges.
/opt/conda/envs/.../lib/python3.9/site-packages/pormake/locator.py:20: UserWarning: Optimal rotation is not uniquely or poorly defined for the given sets of vectors.
  U, rmsd = scipy.spatial.transform.Rotation.align_vectors(p, q)
>>> Start finding bonds in generated framework.
>>> Start finding bonds in building blocks.
>>> Start finding bonds between building blocks.
>>> Start making Framework instance.
>>> Construction of framework done.

Which includes the error I mention:

/opt/conda/envs/.../lib/python3.9/site-packages/pormake/locator.py:20: UserWarning: Optimal rotation is not uniquely or poorly defined for the given sets of vectors.

Does this matter? Are some edge building blocks incompatible with some topologies?

Thanks.

**Comment by Sangwon91** [comment]
In most cases, locating edge building blocks is not an issue,  it is just an alignment of two lines with unit length. So I would say you can disregard that warning.

**Comment by KP-303** [comment]
OK thanks.
